//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLDiemSinhVien : DbContext
    {
        private static QLDiemSinhVien Instance;
        public static QLDiemSinhVien getInstance()
        {
            if (Instance == null)
                Instance = new QLDiemSinhVien();
            return Instance;
        }

        public QLDiemSinhVien()
            : base("name=QLDiemSinhVien")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietDiem> ChiTietDiems { get; set; }
        public virtual DbSet<DiemHocKy> DiemHocKies { get; set; }
        public virtual DbSet<DiemThanhPhan> DiemThanhPhans { get; set; }
        public virtual DbSet<GiangVien> GiangViens { get; set; }
        public virtual DbSet<HinhThucDaoTao> HinhThucDaoTaos { get; set; }
        public virtual DbSet<HocKy> HocKies { get; set; }
        public virtual DbSet<Khoa> Khoas { get; set; }
        public virtual DbSet<Lop> Lops { get; set; }
        public virtual DbSet<LopTinChi> LopTinChis { get; set; }
        public virtual DbSet<MonHoc> MonHocs { get; set; }
        public virtual DbSet<Nganh> Nganhs { get; set; }
        public virtual DbSet<Quyen> Quyens { get; set; }
        public virtual DbSet<SinhVien> SinhViens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoang> TaiKhoangs { get; set; }
    
       
        public virtual int getTongSoTinChiSinhVien(string mssv, string mahk)
        {
            var mssvParameter = mssv != null ?
                new ObjectParameter("mssv", mssv) :
                new ObjectParameter("mssv", typeof(string));
    
            var mahkParameter = mahk != null ?
                new ObjectParameter("mahk", mahk) :
                new ObjectParameter("mahk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("getTongSoTinChiSinhVien", mssvParameter, mahkParameter);
        }
    }
}
